-- Generated by BuildStoredProcedures.ps1. Includes migrations 009 and 010 plus the order/POS procedures.
-- Preserve old orders as UNKNOWN: their creator was not recorded.
USE [portable_kiosk_db];
GO

SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF COL_LENGTH(N'dbo.Orders', N'OrderSource') IS NULL
    ALTER TABLE dbo.Orders ADD OrderSource NVARCHAR(10) NOT NULL
        CONSTRAINT DF_Orders_OrderSource DEFAULT N'UNKNOWN' WITH VALUES;
IF COL_LENGTH(N'dbo.Orders', N'PlacedByStaffAccountID') IS NULL
    ALTER TABLE dbo.Orders ADD PlacedByStaffAccountID INT NULL;
IF COL_LENGTH(N'dbo.Orders', N'PlacedByName') IS NULL
    ALTER TABLE dbo.Orders ADD PlacedByName NVARCHAR(200) NULL;
COMMIT TRANSACTION;
GO

SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_Orders_PlacedByStaffAccount')
    ALTER TABLE dbo.Orders WITH CHECK ADD CONSTRAINT FK_Orders_PlacedByStaffAccount
        FOREIGN KEY (PlacedByStaffAccountID) REFERENCES dbo.StaffAccounts(StaffAccountID) ON DELETE SET NULL;
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_Orders_OrderSource')
    ALTER TABLE dbo.Orders WITH CHECK ADD CONSTRAINT CK_Orders_OrderSource
        CHECK (OrderSource IN (N'UNKNOWN', N'KIOSK', N'POS'));
COMMIT TRANSACTION;
GO

-- Apply after migration 009. New orders snapshot the role at POS processing.
-- Older orders use the linked staff account's current role at migration time;
-- deleted accounts and orders without a recorded processor keep a NULL role.
USE [portable_kiosk_db];
GO

SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF COL_LENGTH(N'dbo.Orders', N'PlacedByStaffAccountID') IS NULL
    THROW 50001, 'Apply migration 009 before adding the order processor role.', 1;
IF COL_LENGTH(N'dbo.Orders', N'ProcessedByRole') IS NULL
    ALTER TABLE dbo.Orders ADD ProcessedByRole NVARCHAR(10) NULL;
COMMIT TRANSACTION;
GO

SET XACT_ABORT ON;
BEGIN TRANSACTION;
UPDATE o
SET ProcessedByRole = staff.StaffRole
FROM dbo.Orders o
INNER JOIN dbo.StaffAccounts staff ON staff.StaffAccountID = o.PlacedByStaffAccountID
WHERE o.ProcessedByRole IS NULL AND staff.StaffRole IN (N'ADMIN', N'CREW');

IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_Orders_ProcessedByRole')
    ALTER TABLE dbo.Orders WITH CHECK ADD CONSTRAINT CK_Orders_ProcessedByRole
        CHECK (ProcessedByRole IS NULL OR ProcessedByRole IN (N'ADMIN', N'CREW'));
COMMIT TRANSACTION;
GO

-- Stored procedures for OrderRepository.
-- Apply after Schema.sql and all required migrations.

CREATE OR ALTER PROCEDURE dbo.Order_GetByID
    @Value INT
AS
BEGIN
    SET NOCOUNT OFF;
    SELECT
        OrderID,
        OrderNumber,
        OrderType,
        FulfillmentMethod,
        TableNumber,
        KitchenStatus,
        ExpiresAt,
        CreatedAt,
        OrderSource,
        PlacedByStaffAccountID,
        PlacedByName,
        ProcessedByRole
    FROM Orders
    WHERE OrderID = @Value;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Order_GetByOrderNumber
    @Value NVARCHAR(20)
AS
BEGIN
    SET NOCOUNT OFF;
    SELECT
        OrderID,
        OrderNumber,
        OrderType,
        FulfillmentMethod,
        TableNumber,
        KitchenStatus,
        ExpiresAt,
        CreatedAt,
        OrderSource,
        PlacedByStaffAccountID,
        PlacedByName,
        ProcessedByRole
    FROM Orders
    WHERE OrderNumber = @Value;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Order_GetAll
AS
BEGIN
    SET NOCOUNT OFF;
    SELECT
        OrderID,
        OrderNumber,
        OrderType,
        FulfillmentMethod,
        TableNumber,
        KitchenStatus,
        ExpiresAt,
        CreatedAt,
        OrderSource,
        PlacedByStaffAccountID,
        PlacedByName,
        ProcessedByRole
    FROM Orders
    ORDER BY CreatedAt DESC, OrderID DESC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Order_GetPaidKitchenOrders
    @IncludeCompleted BIT
AS
BEGIN
    SET NOCOUNT OFF;
    SELECT o.OrderID, o.OrderNumber, o.OrderType,
        o.FulfillmentMethod, o.TableNumber, o.KitchenStatus,
        o.ExpiresAt, o.CreatedAt, o.OrderSource, o.PlacedByStaffAccountID, o.PlacedByName, o.ProcessedByRole
    FROM Orders o
    WHERE (o.KitchenStatus IN (N'QUEUED', N'PREPARING', N'SERVING')
        OR (@IncludeCompleted = 1 AND o.KitchenStatus = N'COMPLETED'))
        AND EXISTS (
            SELECT 1 FROM Payments p
            WHERE p.OrderID = o.OrderID AND p.PaymentStatus = N'PAID'
        )
    ORDER BY o.CreatedAt, o.OrderID;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Order_CancelExpiredPendingOrders
    @ExpiryMinutes INT
AS
BEGIN
    SET NOCOUNT OFF;
    SET NOCOUNT ON;

    DECLARE @ExpiredOrders TABLE (OrderID INT PRIMARY KEY);
    DECLARE @ExpiredCount INT = 0;
    DECLARE @Now DATETIME2(7) = SYSUTCDATETIME();

    UPDATE p
    SET PaymentStatus = N'EXPIRED'
    OUTPUT inserted.OrderID INTO @ExpiredOrders (OrderID)
    FROM Payments p
    INNER JOIN Orders o ON o.OrderID = p.OrderID
    WHERE p.PaymentMethod = N'CASH_COUNTER'
        AND p.PaymentStatus = N'PENDING'
        AND COALESCE(
            o.ExpiresAt,
            DATEADD(
                MINUTE,
                @ExpiryMinutes,
                o.CreatedAt)) <= @Now;

    SET @ExpiredCount = @@ROWCOUNT;

    UPDATE o
    SET KitchenStatus = N'CANCELLED'
    FROM Orders o
    INNER JOIN @ExpiredOrders expired
        ON expired.OrderID = o.OrderID
    WHERE o.KitchenStatus IN (
        N'AWAITING_PAYMENT',
        N'QUEUED'
    );

    SELECT @ExpiredCount;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Order_Update
    @OrderType NVARCHAR(10),
    @FulfillmentMethod NVARCHAR(20),
    @TableNumber NVARCHAR(20),
    @KitchenStatus NVARCHAR(20),
    @ExpiresAt DATETIME2(7),
    @OrderID INT,
    @OrderNumber NVARCHAR(20)
AS
BEGIN
    SET NOCOUNT OFF;
    UPDATE Orders
    SET
        OrderType = @OrderType,
        FulfillmentMethod = @FulfillmentMethod,
        TableNumber = @TableNumber,
        KitchenStatus = @KitchenStatus,
        ExpiresAt = @ExpiresAt
    WHERE OrderID = @OrderID
        AND (
            @KitchenStatus IN (N'AWAITING_PAYMENT', N'CANCELLED')
            OR EXISTS (
                SELECT 1
                FROM Payments p
                WHERE p.OrderID = Orders.OrderID
                    AND p.PaymentStatus = N'PAID'
            )
        );
END;
GO

CREATE OR ALTER PROCEDURE dbo.Order_SetKitchenStatus
    @NextStatus NVARCHAR(20),
    @OrderID INT,
    @CurrentStatus NVARCHAR(20)
AS
BEGIN
    SET NOCOUNT OFF;
    UPDATE Orders
    SET KitchenStatus = @NextStatus
    WHERE OrderID = @OrderID AND KitchenStatus = @CurrentStatus
        AND EXISTS (SELECT 1 FROM Payments
            WHERE Payments.OrderID = Orders.OrderID
                AND PaymentStatus = N'PAID');
END;
GO

CREATE OR ALTER PROCEDURE dbo.Order_Delete
    @OrderID INT
AS
BEGIN
    SET NOCOUNT OFF;
    DELETE FROM Orders
    WHERE OrderID = @OrderID;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Order_Add_Insert
    @OrderNumber NVARCHAR(20),
    @OrderType NVARCHAR(10),
    @FulfillmentMethod NVARCHAR(20),
    @TableNumber NVARCHAR(20),
    @KitchenStatus NVARCHAR(20),
    @ExpiresAt DATETIME2(7),
    @OrderSource NVARCHAR(10) = N'KIOSK',
    @PlacedByStaffAccountID INT = NULL
AS
BEGIN
    SET NOCOUNT OFF;
    DECLARE @PlacedByName NVARCHAR(200);
    DECLARE @ProcessedByRole NVARCHAR(10);
    IF @OrderSource IS NULL OR @OrderSource NOT IN (N'KIOSK', N'POS')
        THROW 50001, 'Invalid order source.', 1;
    IF @OrderSource = N'POS'
    BEGIN
        -- Snapshot the processor's name and role so later account changes retain order history.
        SELECT @PlacedByName = CONCAT(FirstName, N' ',
            CASE WHEN NULLIF(LTRIM(RTRIM(MiddleName)), N'') IS NULL THEN N'' ELSE MiddleName + N' ' END,
            LastName, CASE WHEN NULLIF(LTRIM(RTRIM(Suffix)), N'') IS NULL THEN N'' ELSE N' ' + Suffix END),
            @ProcessedByRole = StaffRole
        FROM dbo.StaffAccounts
        WHERE StaffAccountID = @PlacedByStaffAccountID
            AND IsActive = 1 AND StaffRole IN (N'ADMIN', N'CREW');
        IF @PlacedByName IS NULL
            THROW 50002, 'An active staff account is required for a POS order.', 1;
    END
    ELSE IF @PlacedByStaffAccountID IS NOT NULL
        THROW 50003, 'Kiosk orders cannot have a staff creator.', 1;
    INSERT INTO Orders
        (
            OrderNumber,
            OrderSource,
            PlacedByStaffAccountID,
            PlacedByName,
            ProcessedByRole,
            OrderType,
            FulfillmentMethod,
            TableNumber,
            KitchenStatus,
            ExpiresAt
        )
    OUTPUT INSERTED.OrderID, INSERTED.CreatedAt, INSERTED.PlacedByName, INSERTED.ProcessedByRole
    VALUES
        (
            @OrderNumber,
            @OrderSource,
            @PlacedByStaffAccountID,
            @PlacedByName,
            @ProcessedByRole,
            @OrderType,
            @FulfillmentMethod,
            @TableNumber,
            @KitchenStatus,
            @ExpiresAt
        );
END;
GO

CREATE OR ALTER PROCEDURE dbo.Order_Add_UpdateNumber
    @OrderNumber NVARCHAR(20),
    @OrderID INT
AS
BEGIN
    SET NOCOUNT OFF;
    UPDATE Orders
    SET OrderNumber = @OrderNumber
    WHERE OrderID = @OrderID;
END;
GO

-- Stored procedures for PosRepository.
-- Apply after Schema.sql and all required migrations.

CREATE OR ALTER PROCEDURE dbo.Pos_CompleteNewCashSale_Lock
    @Resource NVARCHAR(255)
AS
BEGIN
    SET NOCOUNT OFF;
    DECLARE @Result INT;
    EXEC @Result = sp_getapplock
        @Resource = @Resource,
        @LockMode = N'Exclusive',
        @LockOwner = N'Transaction',
        @LockTimeout = 10000;
    SELECT @Result;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Pos_CompleteNewCashSale_Existing
    @Reference NVARCHAR(100)
AS
BEGIN
    SET NOCOUNT OFF;
    SELECT o.OrderID, o.OrderNumber, o.OrderType,
        o.FulfillmentMethod, o.TableNumber, o.KitchenStatus,
        o.CreatedAt, o.ExpiresAt, o.OrderSource, o.PlacedByStaffAccountID, o.PlacedByName, o.ProcessedByRole, p.PaymentID, p.Amount, p.PaidAt
    FROM Payments p
    INNER JOIN Orders o ON o.OrderID = p.OrderID
    WHERE p.TransactionReference = @Reference
        AND p.PaymentMethod IN (N'CASH_COUNTER', N'CASHLESS')
        AND p.PaymentStatus = N'PAID';
END;
GO

CREATE OR ALTER PROCEDURE dbo.Pos_GetAvailableCatalog
AS
BEGIN
    SET NOCOUNT OFF;
    SELECT
        pv.ProductVariantID,
        pv.ProductID,
        c.CategoryID,
        pv.SizeID,
        p.ProductName,
        c.CategoryName,
        s.SizeName,
        pv.ImagePath,
        pv.Price
    FROM ProductVariants pv
    INNER JOIN Products p ON p.ProductID = pv.ProductID
    INNER JOIN Categories c ON c.CategoryID = p.CategoryID
    LEFT JOIN Sizes s ON s.SizeID = pv.SizeID
    WHERE pv.IsAvailable = 1
        AND p.IsAvailable = 1
        AND c.IsAvailable = 1
    ORDER BY c.CategoryName, p.ProductName,
        pv.Price, pv.ProductVariantID;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Pos_CompleteKioskCashOrder_Lock
    @ExpiryMinutes INT,
    @OrderID INT
AS
BEGIN
    SET NOCOUNT OFF;
    SELECT
        o.OrderID,
        o.OrderNumber,
        o.OrderType,
        o.FulfillmentMethod,
        o.TableNumber,
        o.KitchenStatus,
        o.CreatedAt,
        o.ExpiresAt,
        o.OrderSource,
        o.PlacedByStaffAccountID,
        o.PlacedByName,
        o.ProcessedByRole,
        COALESCE(
            o.ExpiresAt,
            DATEADD(MINUTE, @ExpiryMinutes, o.CreatedAt)
        ) AS EffectiveExpiresAt,
        p.PaymentID,
        p.PaymentMethod,
        p.PaymentStatus
    FROM Payments p WITH (UPDLOCK, HOLDLOCK)
    INNER JOIN Orders o WITH (UPDLOCK, HOLDLOCK)
        ON o.OrderID = p.OrderID
    WHERE p.OrderID = @OrderID;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Pos_CompleteKioskCashOrder_DeleteItems
    @OrderID INT
AS
BEGIN
    SET NOCOUNT OFF;
    DELETE FROM OrderItems WHERE OrderID = @OrderID;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Pos_CompleteKioskCashOrder_CurrentItems
    @OrderID INT
AS
BEGIN
    SET NOCOUNT OFF;
    SELECT OrderItemID, ProductVariantID, UnitPrice, Quantity
    FROM OrderItems WITH (UPDLOCK, HOLDLOCK)
    WHERE OrderID = @OrderID
    ORDER BY OrderItemID;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Pos_CompleteKioskCashOrder_Pay
    @PaymentMethod NVARCHAR(20),
    @Amount DECIMAL(10,2),
    @TransactionReference NVARCHAR(100),
    @PaidAt DATETIME2(7),
    @OrderID INT
AS
BEGIN
    SET NOCOUNT OFF;
    UPDATE Payments
    SET PaymentMethod = @PaymentMethod,
        PaymentStatus = N'PAID',
        Amount = @Amount,
        TransactionReference = @TransactionReference,
        PaidAt = @PaidAt
    WHERE OrderID = @OrderID
        AND PaymentMethod = N'CASH_COUNTER'
        AND PaymentStatus = N'PENDING';
END;
GO

CREATE OR ALTER PROCEDURE dbo.Pos_CompleteKioskCashOrder_Queue
    @OrderID INT,
    @ExpiryMinutes INT,
    @PlacedByStaffAccountID INT
AS
BEGIN
    SET NOCOUNT OFF;
    DECLARE @PlacedByName NVARCHAR(200);
    DECLARE @ProcessedByRole NVARCHAR(10);
    -- Save the crew who accepts payment, including orders started on the kiosk.
    SELECT @PlacedByName = CONCAT(FirstName, N' ',
        CASE WHEN NULLIF(LTRIM(RTRIM(MiddleName)), N'') IS NULL THEN N'' ELSE MiddleName + N' ' END,
        LastName, CASE WHEN NULLIF(LTRIM(RTRIM(Suffix)), N'') IS NULL THEN N'' ELSE N' ' + Suffix END),
        @ProcessedByRole = StaffRole
    FROM dbo.StaffAccounts
    WHERE StaffAccountID = @PlacedByStaffAccountID
        AND IsActive = 1 AND StaffRole IN (N'ADMIN', N'CREW');
    IF @PlacedByName IS NULL
        THROW 50002, 'An active staff account is required to process an order.', 1;
    UPDATE Orders
    SET KitchenStatus = N'QUEUED', ExpiresAt = NULL,
        PlacedByStaffAccountID = @PlacedByStaffAccountID,
        PlacedByName = @PlacedByName,
        ProcessedByRole = @ProcessedByRole
    OUTPUT INSERTED.PlacedByStaffAccountID, INSERTED.PlacedByName, INSERTED.ProcessedByRole
    WHERE OrderID = @OrderID
        AND KitchenStatus = N'AWAITING_PAYMENT'
        AND COALESCE(
            ExpiresAt,
            DATEADD(MINUTE, @ExpiryMinutes, CreatedAt)
        ) > SYSUTCDATETIME();
END;
GO
