//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.User
{
    public partial class CartPage
    {
        protected global::System.Web.UI.WebControls.Label lblCartMessage;
        protected global::System.Web.UI.WebControls.Panel pnlEmptyCart;
        protected global::System.Web.UI.WebControls.Panel pnlCart;
        protected global::System.Web.UI.WebControls.Repeater rptCartItems;
        protected global::System.Web.UI.WebControls.Literal litTotalQuantity;
        protected global::System.Web.UI.WebControls.Literal litTotalAmount;
        protected global::System.Web.UI.WebControls.Button btnProceedToCheckout;
    }
}
