//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.User
{
    public partial class Complete
    {
        protected global::System.Web.UI.WebControls.Literal litOrderNumber;
        protected global::System.Web.UI.WebControls.Literal litOrderType;
        protected global::System.Web.UI.WebControls.Repeater rptOrderItems;
        protected global::System.Web.UI.WebControls.Literal litInstruction;
        protected global::System.Web.UI.WebControls.Panel completeExpiry;
        protected global::System.Web.UI.WebControls.Literal litExpiryLabel;
        protected global::System.Web.UI.WebControls.Literal litExpiryTime;
        protected global::System.Web.UI.WebControls.Literal litExpiryHint;
        protected global::System.Web.UI.WebControls.Button btnFinish;
    }
}
