//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.User
{
    public partial class Fulfillment
    {
        protected global::System.Web.UI.WebControls.Literal litFulfillmentHint;
        protected global::System.Web.UI.WebControls.Panel pnlTableService;
        protected global::System.Web.UI.WebControls.LinkButton btnTableService;
        protected global::System.Web.UI.WebControls.LinkButton btnCounterPickup;
    }
}
