//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.User
{
    public partial class Menu
    {
        /// <summary>
        /// pnlAddSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAddSuccess;

        /// <summary>
        /// litAddSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAddSuccess;

        protected global::System.Web.UI.WebControls.LinkButton btnHome;
        protected global::System.Web.UI.WebControls.Repeater rptCategories;
        protected global::System.Web.UI.WebControls.Label lblMenuError;
        protected global::System.Web.UI.WebControls.Panel pnlHome;
        protected global::System.Web.UI.WebControls.Panel pnlProducts;
        protected global::System.Web.UI.WebControls.Literal litCategoryName;
        protected global::System.Web.UI.WebControls.Panel pnlNoProducts;
        protected global::System.Web.UI.WebControls.Repeater rptProducts;
        protected global::System.Web.UI.WebControls.Literal litSelectedProductName;
        protected global::System.Web.UI.WebControls.Image imgSelectedProduct;
        protected global::System.Web.UI.WebControls.Panel pnlSelectedProductPlaceholder;
        protected global::System.Web.UI.WebControls.Literal litSelectedProductDescription;
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedProductID;
        protected global::System.Web.UI.WebControls.RadioButtonList rblVariants;
        protected global::System.Web.UI.WebControls.TextBox txtQuantity;
        protected global::System.Web.UI.WebControls.Label lblProductError;
        protected global::System.Web.UI.WebControls.Button btnAddToCart;
    }
}
