//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.User
{
    public partial class OnlinePayment
    {
        protected global::System.Web.UI.WebControls.Literal litPaymentTotal;
        protected global::System.Web.UI.WebControls.Button btnConfirmMockPayment;
    }
}
