//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.User
{
    public partial class OrderType
    {
        protected global::System.Web.UI.WebControls.Button btnDineIn;

        protected global::System.Web.UI.WebControls.Button btnTakeout;
    }
}
