//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.User
{
    public partial class Payment
    {
        protected global::System.Web.UI.WebControls.LinkButton btnCashless;

        protected global::System.Web.UI.WebControls.LinkButton btnCashCounter;

    }
}
