//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.Shared.Layouts
{
    public partial class UserLayout
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl userKioskShell;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl userKioskHeader;

        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkMenu;

        protected global::System.Web.UI.WebControls.Literal litOrderType;

        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkCart;

        protected global::System.Web.UI.WebControls.Literal litCartCount;

        protected global::System.Web.UI.WebControls.Literal litCartTotal;

        protected global::System.Web.UI.WebControls.Button btnCancelOrder;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder UserContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder UserScriptsContent;
    }
}
