//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.Admin
{
    public partial class BundleManagement
    {
        protected global::System.Web.UI.WebControls.Label lblGlobalMessage;

        protected global::System.Web.UI.WebControls.ValidationSummary validationSummaryBundle;
        protected global::System.Web.UI.WebControls.Label lblBundleName;
        protected global::System.Web.UI.WebControls.TextBox txtBundleName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredBundleName;
        protected global::System.Web.UI.WebControls.Label lblBasePrice;
        protected global::System.Web.UI.WebControls.TextBox txtBasePrice;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredBasePrice;
        protected global::System.Web.UI.WebControls.RangeValidator rangeBasePrice;
        protected global::System.Web.UI.WebControls.Label lblBundleImage;
        protected global::System.Web.UI.WebControls.FileUpload uploadBundleImage;
        protected global::System.Web.UI.WebControls.Label lblBundleDisplayOrder;
        protected global::System.Web.UI.WebControls.TextBox txtBundleDisplayOrder;
        protected global::System.Web.UI.WebControls.CheckBox chkBundleIsAvailable;
        protected global::System.Web.UI.WebControls.Button btnAddBundle;
        protected global::System.Web.UI.WebControls.Label lblBundleStats;
        protected global::System.Web.UI.WebControls.Repeater rptBundleCards;
        protected global::System.Web.UI.WebControls.Panel pnlNoBundles;

        protected global::System.Web.UI.WebControls.ValidationSummary validationSummaryOptionGroup;
        protected global::System.Web.UI.WebControls.Label lblOptionGroupName;
        protected global::System.Web.UI.WebControls.TextBox txtOptionGroupName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredOptionGroupName;
        protected global::System.Web.UI.WebControls.Label lblOptionGroupDisplayOrder;
        protected global::System.Web.UI.WebControls.TextBox txtOptionGroupDisplayOrder;
        protected global::System.Web.UI.WebControls.CheckBox chkOptionGroupIsAvailable;
        protected global::System.Web.UI.WebControls.Button btnAddOptionGroup;
        protected global::System.Web.UI.WebControls.Label lblOptionGroupStats;
        protected global::System.Web.UI.WebControls.Repeater rptOptionGroupCards;
        protected global::System.Web.UI.WebControls.Panel pnlNoOptionGroups;

        protected global::System.Web.UI.WebControls.ValidationSummary validationSummarySlot;
        protected global::System.Web.UI.WebControls.HiddenField hfModalSlotBundleID;
        protected global::System.Web.UI.WebControls.Label lblModalSlotName;
        protected global::System.Web.UI.WebControls.TextBox txtModalSlotName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredModalSlotName;
        protected global::System.Web.UI.WebControls.Label lblModalSlotType;
        protected global::System.Web.UI.WebControls.DropDownList ddlModalSlotType;
        protected global::System.Web.UI.WebControls.Label lblModalFixedVariant;
        protected global::System.Web.UI.WebControls.DropDownList ddlModalFixedVariant;
        protected global::System.Web.UI.WebControls.Label lblModalOptionGroup;
        protected global::System.Web.UI.WebControls.DropDownList ddlModalOptionGroup;
        protected global::System.Web.UI.WebControls.Label lblModalSlotQuantity;
        protected global::System.Web.UI.WebControls.TextBox txtModalSlotQuantity;
        protected global::System.Web.UI.WebControls.Label lblModalSlotDisplayOrder;
        protected global::System.Web.UI.WebControls.TextBox txtModalSlotDisplayOrder;
        protected global::System.Web.UI.WebControls.CheckBox chkModalSlotIsRequired;
        protected global::System.Web.UI.WebControls.Button btnSaveSlot;

        protected global::System.Web.UI.WebControls.ValidationSummary validationSummaryGroupItem;
        protected global::System.Web.UI.WebControls.HiddenField hfModalOptionGroupID;
        protected global::System.Web.UI.WebControls.Label lblModalGroupItemVariant;
        protected global::System.Web.UI.WebControls.DropDownList ddlModalGroupItemVariant;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredModalGroupItemVariant;
        protected global::System.Web.UI.WebControls.Label lblModalGroupItemAddPrice;
        protected global::System.Web.UI.WebControls.TextBox txtModalGroupItemAddPrice;
        protected global::System.Web.UI.WebControls.Label lblModalGroupItemDisplayOrder;
        protected global::System.Web.UI.WebControls.TextBox txtModalGroupItemDisplayOrder;
        protected global::System.Web.UI.WebControls.CheckBox chkModalGroupItemIsAvailable;
        protected global::System.Web.UI.WebControls.Button btnSaveGroupItem;
    }
}
