//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.Admin
{
    public partial class BundleSlotManagement
    {
        protected global::System.Web.UI.WebControls.ValidationSummary validationSummary;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.Label lblBundle;

        protected global::System.Web.UI.WebControls.DropDownList ddlBundle;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredBundle;

        protected global::System.Web.UI.WebControls.Label lblSlotName;

        protected global::System.Web.UI.WebControls.TextBox txtSlotName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredSlotName;

        protected global::System.Web.UI.WebControls.Label lblSlotType;

        protected global::System.Web.UI.WebControls.DropDownList ddlSlotType;

        protected global::System.Web.UI.WebControls.Panel pnlFixedProduct;

        protected global::System.Web.UI.WebControls.Label lblFixedProductVariant;

        protected global::System.Web.UI.WebControls.DropDownList ddlFixedProductVariant;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredFixedProductVariant;

        protected global::System.Web.UI.WebControls.Panel pnlOptionGroup;

        protected global::System.Web.UI.WebControls.Label lblOptionGroup;

        protected global::System.Web.UI.WebControls.DropDownList ddlOptionGroup;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredOptionGroup;

        protected global::System.Web.UI.WebControls.Panel pnlDefaultProductVariant;

        protected global::System.Web.UI.WebControls.Label lblDefaultProductVariant;

        protected global::System.Web.UI.WebControls.DropDownList ddlDefaultProductVariant;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredDefaultProductVariant;

        protected global::System.Web.UI.WebControls.Label lblQuantity;

        protected global::System.Web.UI.WebControls.TextBox txtQuantity;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredQuantity;

        protected global::System.Web.UI.WebControls.RangeValidator rangeQuantity;

        protected global::System.Web.UI.WebControls.Label lblDisplayOrder;

        protected global::System.Web.UI.WebControls.TextBox txtDisplayOrder;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredDisplayOrder;

        protected global::System.Web.UI.WebControls.RangeValidator rangeDisplayOrder;

        protected global::System.Web.UI.WebControls.CheckBox chkIsRequired;

        protected global::System.Web.UI.WebControls.Button btnAddSlot;

        protected global::System.Web.UI.WebControls.Label lblLoadError;

        protected global::System.Web.UI.WebControls.GridView gridSlots;
    }
}
