//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.Admin
{
    public partial class BundleOptionGroupItemManagement
    {
        protected global::System.Web.UI.WebControls.ValidationSummary validationSummary;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.Label lblOptionGroup;

        protected global::System.Web.UI.WebControls.DropDownList ddlOptionGroup;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredOptionGroup;

        protected global::System.Web.UI.WebControls.Label lblProductVariant;

        protected global::System.Web.UI.WebControls.DropDownList ddlProductVariant;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredProductVariant;

        protected global::System.Web.UI.WebControls.Label lblAdditionalPrice;

        protected global::System.Web.UI.WebControls.TextBox txtAdditionalPrice;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredAdditionalPrice;

        protected global::System.Web.UI.WebControls.RangeValidator rangeAdditionalPrice;

        protected global::System.Web.UI.WebControls.Label lblDisplayOrder;

        protected global::System.Web.UI.WebControls.TextBox txtDisplayOrder;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredDisplayOrder;

        protected global::System.Web.UI.WebControls.RangeValidator rangeDisplayOrder;

        protected global::System.Web.UI.WebControls.CheckBox chkIsAvailable;

        protected global::System.Web.UI.WebControls.Button btnAddItem;

        protected global::System.Web.UI.WebControls.Label lblLoadError;

        protected global::System.Web.UI.WebControls.GridView gridItems;
    }
}
