//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.Admin
{
    public partial class CatalogConfig
    {
        protected global::System.Web.UI.WebControls.ValidationSummary validationSummaryCategory;
        protected global::System.Web.UI.WebControls.Label lblCategoryMessage;
        protected global::System.Web.UI.WebControls.Label lblCategoryName;
        protected global::System.Web.UI.WebControls.TextBox txtCategoryName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredCategoryName;
        protected global::System.Web.UI.WebControls.CheckBox chkCategoryIsAvailable;
        protected global::System.Web.UI.WebControls.Button btnAddCategory;
        protected global::System.Web.UI.WebControls.Label lblCategoryCount;
        protected global::System.Web.UI.WebControls.Label lblCategoryLoadError;
        protected global::System.Web.UI.WebControls.GridView gridCategories;
        protected global::System.Web.UI.WebControls.ValidationSummary validationSummaryEditCategory;
        protected global::System.Web.UI.WebControls.HiddenField hfEditCategoryID;
        protected global::System.Web.UI.WebControls.Label lblEditCategoryName;
        protected global::System.Web.UI.WebControls.TextBox txtEditCategoryName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredEditCategoryName;
        protected global::System.Web.UI.WebControls.CheckBox chkEditCategoryIsAvailable;
        protected global::System.Web.UI.WebControls.Button btnUpdateCategory;
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteCategoryID;
        protected global::System.Web.UI.WebControls.Button btnDeleteCategory;

        protected global::System.Web.UI.WebControls.ValidationSummary validationSummarySize;
        protected global::System.Web.UI.WebControls.Label lblSizeMessage;
        protected global::System.Web.UI.WebControls.Label lblSizeName;
        protected global::System.Web.UI.WebControls.TextBox txtSizeName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredSizeName;
        protected global::System.Web.UI.WebControls.Button btnAddSize;
        protected global::System.Web.UI.WebControls.Label lblSizeCount;
        protected global::System.Web.UI.WebControls.Label lblSizeLoadError;
        protected global::System.Web.UI.WebControls.GridView gridSizes;
        protected global::System.Web.UI.WebControls.ValidationSummary validationSummaryEditSize;
        protected global::System.Web.UI.WebControls.HiddenField hfEditSizeID;
        protected global::System.Web.UI.WebControls.Label lblEditSizeName;
        protected global::System.Web.UI.WebControls.TextBox txtEditSizeName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredEditSizeName;
        protected global::System.Web.UI.WebControls.Button btnUpdateSize;
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteSizeID;
        protected global::System.Web.UI.WebControls.Button btnDeleteSize;
    }
}
