//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.Admin
{
    public partial class Orders
    {
        protected global::System.Web.UI.WebControls.Label lblOrderCount;
        protected global::System.Web.UI.WebControls.Label lblOrderSearch;
        protected global::System.Web.UI.WebControls.TextBox txtOrderSearch;
        protected global::System.Web.UI.WebControls.Button btnSearchOrders;
        protected global::System.Web.UI.WebControls.Label lblPaymentStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlPaymentStatus;
        protected global::System.Web.UI.WebControls.GridView gridOrders;
        protected global::System.Web.UI.WebControls.Literal litDetailsOrderNumber;
        protected global::System.Web.UI.WebControls.Literal litDetailsCreatedAt;
        protected global::System.Web.UI.WebControls.Literal litDetailsExpiresAt;
        protected global::System.Web.UI.WebControls.Literal litDetailsOrderType;
        protected global::System.Web.UI.WebControls.Literal litDetailsFulfillment;
        protected global::System.Web.UI.WebControls.Label lblDetailsKitchenStatus;
        protected global::System.Web.UI.WebControls.Label lblDetailsPaymentStatus;
        protected global::System.Web.UI.WebControls.Panel pnlOrderItems;
        protected global::System.Web.UI.WebControls.Repeater rptOrderItems;
        protected global::System.Web.UI.WebControls.Panel pnlNoOrderItems;
        protected global::System.Web.UI.WebControls.Literal litDetailsPayment;
        protected global::System.Web.UI.WebControls.Literal litDetailsTotal;
    }
}
