//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.Admin
{
    public partial class ProductManagement
    {
        protected global::System.Web.UI.WebControls.Label lblGlobalMessage;
        protected global::System.Web.UI.WebControls.ValidationSummary validationSummaryProduct;
        protected global::System.Web.UI.WebControls.Label lblCategory;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredCategory;
        protected global::System.Web.UI.WebControls.Label lblProductName;
        protected global::System.Web.UI.WebControls.TextBox txtProductName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredProductName;
        protected global::System.Web.UI.WebControls.Label lblDisplayOrder;
        protected global::System.Web.UI.WebControls.TextBox txtDisplayOrder;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredDisplayOrder;
        protected global::System.Web.UI.WebControls.RangeValidator rangeDisplayOrder;
        protected global::System.Web.UI.WebControls.CheckBox chkIsAvailable;
        protected global::System.Web.UI.WebControls.Button btnAddProduct;
        protected global::System.Web.UI.WebControls.Label lblProductStats;
        protected global::System.Web.UI.WebControls.Label lblLoadError;
        protected global::System.Web.UI.WebControls.Repeater rptProductCards;
        protected global::System.Web.UI.WebControls.Panel pnlNoProducts;

        protected global::System.Web.UI.WebControls.ValidationSummary validationSummaryVariant;
        protected global::System.Web.UI.WebControls.HiddenField hfModalProductID;
        protected global::System.Web.UI.WebControls.Label lblModalSize;
        protected global::System.Web.UI.WebControls.DropDownList ddlModalSize;
        protected global::System.Web.UI.WebControls.Label lblModalPrice;
        protected global::System.Web.UI.WebControls.TextBox txtModalPrice;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredModalPrice;
        protected global::System.Web.UI.WebControls.RangeValidator rangeModalPrice;
        protected global::System.Web.UI.WebControls.Label lblModalImage;
        protected global::System.Web.UI.WebControls.FileUpload uploadModalImage;
        protected global::System.Web.UI.WebControls.CheckBox chkModalIsAvailable;
        protected global::System.Web.UI.WebControls.Button btnSaveModalVariant;
    }
}
