//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableKiosk.UI.Admin
{
    public partial class ProductManagement
    {
        protected global::System.Web.UI.WebControls.Label lblGlobalMessage;
        protected global::System.Web.UI.WebControls.ValidationSummary validationSummaryProduct;
        protected global::System.Web.UI.WebControls.Label lblCategory;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredCategory;
        protected global::System.Web.UI.WebControls.Label lblProductName;
        protected global::System.Web.UI.WebControls.TextBox txtProductName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredProductName;
        protected global::System.Web.UI.WebControls.CheckBox chkIsAvailable;
        protected global::System.Web.UI.WebControls.Button btnAddProduct;

        protected global::System.Web.UI.WebControls.ValidationSummary validationSummaryEditProduct;
        protected global::System.Web.UI.WebControls.HiddenField hfEditProductID;
        protected global::System.Web.UI.WebControls.Label lblEditProductCategory;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditProductCategory;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredEditProductCategory;
        protected global::System.Web.UI.WebControls.Label lblEditProductName;
        protected global::System.Web.UI.WebControls.TextBox txtEditProductName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredEditProductName;
        protected global::System.Web.UI.WebControls.Label lblEditProductDescription;
        protected global::System.Web.UI.WebControls.TextBox txtEditProductDescription;
        protected global::System.Web.UI.WebControls.CheckBox chkEditProductIsAvailable;
        protected global::System.Web.UI.WebControls.Button btnUpdateProduct;

        protected global::System.Web.UI.WebControls.HiddenField hfDeleteProductID;
        protected global::System.Web.UI.WebControls.Button btnDeleteProduct;

        protected global::System.Web.UI.WebControls.Label lblLoadError;
        protected global::System.Web.UI.WebControls.Repeater rptCategoryGroups;
        protected global::System.Web.UI.WebControls.Panel pnlNoProducts;

        protected global::System.Web.UI.WebControls.ValidationSummary validationSummaryVariant;
        protected global::System.Web.UI.WebControls.HiddenField hfModalProductID;
        protected global::System.Web.UI.WebControls.Repeater rptBulkVariantRows;
        protected global::System.Web.UI.WebControls.CheckBox chkModalIsAvailable;
        protected global::System.Web.UI.WebControls.Button btnSaveModalVariant;

        protected global::System.Web.UI.WebControls.ValidationSummary validationSummaryEditVariant;
        protected global::System.Web.UI.WebControls.HiddenField hfEditVariantID;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditVariantSize;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredEditVariantSize;
        protected global::System.Web.UI.WebControls.TextBox txtEditVariantPrice;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator requiredEditVariantPrice;
        protected global::System.Web.UI.WebControls.RangeValidator rangeEditVariantPrice;
        protected global::System.Web.UI.WebControls.FileUpload uploadEditVariantImage;
        protected global::System.Web.UI.WebControls.CheckBox chkEditVariantIsAvailable;
        protected global::System.Web.UI.WebControls.Button btnUpdateVariant;

        protected global::System.Web.UI.WebControls.HiddenField hfDeleteVariantID;
        protected global::System.Web.UI.WebControls.Button btnDeleteVariant;
    }
}
