$ErrorActionPreference = 'Stop'
$header = @'
-- Generated from StoredProcedures/*.sql by BuildStoredProcedures.ps1.
-- Run against the application database after applying schema/migrations.
USE [portable_kiosk_db];
GO

'@
$files = Get-ChildItem -LiteralPath (Join-Path $PSScriptRoot 'StoredProcedures') -Filter '*.sql' | Sort-Object Name
$body = ($files | ForEach-Object { [System.IO.File]::ReadAllText($_.FullName) }) -join "`r`n"
[System.IO.File]::WriteAllText((Join-Path $PSScriptRoot 'InstallStoredProcedures.sql'), $header + "`r`n" + $body, [System.Text.UTF8Encoding]::new($false))
Write-Output "Built InstallStoredProcedures.sql from $($files.Count) repository files."

# Focused upgrade for existing installations; does not rebuild tables or renumber orders.
$upgradeDirectory = Join-Path $PSScriptRoot 'Migrations/Upgrades'
New-Item -ItemType Directory -Path $upgradeDirectory -Force | Out-Null
$analyticsUpgrade = [System.IO.File]::ReadAllText((Join-Path $PSScriptRoot 'Migrations/008_DISABLE_IDENTITY_CACHE.sql')) + "`r`n" +
    [System.IO.File]::ReadAllText((Join-Path $PSScriptRoot 'StoredProcedures/AnalyticsRepository.sql'))
[System.IO.File]::WriteAllText((Join-Path $upgradeDirectory 'UPDATE ANALYTICS AND ORDER NUMBER CACHE.sql'),
    "-- Generated by BuildStoredProcedures.ps1. Run this whole file against your existing application database.`r`n" + $analyticsUpgrade,
    [System.Text.UTF8Encoding]::new($false))
Write-Output 'Built UPDATE ANALYTICS AND ORDER NUMBER CACHE.sql.'

$placedByUpgrade = [System.IO.File]::ReadAllText((Join-Path $PSScriptRoot 'Migrations/009_ADD_ORDER_PLACED_BY.sql')) + "`r`n" +
    [System.IO.File]::ReadAllText((Join-Path $PSScriptRoot 'Migrations/010_ADD_ORDER_PROCESSOR_ROLE.sql')) + "`r`n" +
    [System.IO.File]::ReadAllText((Join-Path $PSScriptRoot 'StoredProcedures/OrderRepository.sql')) + "`r`n" +
    [System.IO.File]::ReadAllText((Join-Path $PSScriptRoot 'StoredProcedures/PosRepository.sql'))
[System.IO.File]::WriteAllText((Join-Path $upgradeDirectory 'UPDATE ORDER PLACED BY.sql'),
    "-- Generated by BuildStoredProcedures.ps1. Run this whole file once on an existing database.`r`n" + $placedByUpgrade,
    [System.Text.UTF8Encoding]::new($false))
Write-Output 'Built UPDATE ORDER PLACED BY.sql.'

[System.IO.File]::WriteAllText((Join-Path $upgradeDirectory 'UPDATE ORDER PROCESSOR ROLE.sql'),
    "-- Generated by BuildStoredProcedures.ps1. Includes migrations 009 and 010 plus the order/POS procedures.`r`n" + $placedByUpgrade,
    [System.Text.UTF8Encoding]::new($false))
Write-Output 'Built UPDATE ORDER PROCESSOR ROLE.sql.'
