-- Generated by BuildStoredProcedures.ps1. Run this whole file against your existing application database.
-- Prevent large identity jumps when SQL Server restarts or fails over.
-- OrderRepository formats OrderID as the customer-facing order number (D4).
-- Keeps all existing order IDs/numbers. Failed inserts and deletions can still leave gaps.
USE [portable_kiosk_db];
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = OFF;
GO

CHECKPOINT;
GO

SELECT name, value
FROM sys.database_scoped_configurations
WHERE name = N'IDENTITY_CACHE';
GO

-- Stored procedures for AnalyticsRepository.
-- Apply after Schema.sql and all required migrations.

CREATE OR ALTER PROCEDURE dbo.Analytics_ReadSummary
    @Start DATETIME2(7),
    @End DATETIME2(7)
AS
BEGIN
    SET NOCOUNT OFF;
    SELECT COALESCE(SUM(Amount), 0), COUNT(*)
    FROM Payments WHERE PaymentStatus = N'PAID' AND PaidAt >= @Start AND PaidAt < @End;
    SELECT COUNT(*), COALESCE(SUM(CASE WHEN p.PaymentStatus = N'PAID' THEN 1 ELSE 0 END), 0),
        COALESCE(SUM(CASE WHEN p.PaymentStatus = N'PAID' THEN p.Amount ELSE 0 END), 0),
        COALESCE(SUM(CASE WHEN p.PaymentStatus = N'EXPIRED'
            OR (p.PaymentStatus = N'PENDING' AND o.ExpiresAt IS NOT NULL
                AND o.ExpiresAt <= SYSUTCDATETIME()) THEN 1 ELSE 0 END), 0),
        COALESCE(SUM(CASE WHEN p.PaymentStatus = N'EXPIRED'
            OR (p.PaymentStatus = N'PENDING' AND o.ExpiresAt IS NOT NULL
                AND o.ExpiresAt <= SYSUTCDATETIME()) THEN p.Amount ELSE 0 END), 0)
    FROM Orders o LEFT JOIN Payments p ON p.OrderID = o.OrderID
    WHERE o.CreatedAt >= @Start AND o.CreatedAt < @End;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Analytics_ReadTrend
    @Monthly BIT,
    @Start DATETIME2(7),
    @End DATETIME2(7)
AS
BEGIN
    SET NOCOUNT OFF;
    SELECT CASE WHEN @Monthly = 1
        THEN DATEFROMPARTS(YEAR(DATEADD(HOUR, 8, PaidAt)), MONTH(DATEADD(HOUR, 8, PaidAt)), 1)
        ELSE CAST(DATEADD(HOUR, 8, PaidAt) AS date) END AS Bucket, SUM(Amount)
    FROM Payments WHERE PaymentStatus = N'PAID' AND PaidAt >= @Start AND PaidAt < @End
    GROUP BY CASE WHEN @Monthly = 1
        THEN DATEFROMPARTS(YEAR(DATEADD(HOUR, 8, PaidAt)), MONTH(DATEADD(HOUR, 8, PaidAt)), 1)
        ELSE CAST(DATEADD(HOUR, 8, PaidAt) AS date) END
    ORDER BY 1;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Analytics_ReadProducts
    @Start DATETIME2(7),
    @End DATETIME2(7)
AS
BEGIN
    SET NOCOUNT OFF;
    SELECT p.ProductName, COALESCE(SUM(oi.Quantity), 0) AS Units,
        COALESCE(SUM(oi.UnitPrice * oi.Quantity), 0) AS Revenue,
        CASE WHEN p.IsAvailable = 1 AND c.IsAvailable = 1
            AND EXISTS (SELECT 1 FROM ProductVariants available
                WHERE available.ProductID = p.ProductID AND available.IsAvailable = 1)
            THEN 1 ELSE 0 END AS OnMenu,
        (SELECT TOP (1) imageVariant.ImagePath
            FROM ProductVariants imageVariant
            WHERE imageVariant.ProductID = p.ProductID
                AND imageVariant.ImagePath IS NOT NULL
                AND LTRIM(RTRIM(imageVariant.ImagePath)) <> N''
            ORDER BY imageVariant.IsAvailable DESC,
                imageVariant.ProductVariantID) AS ImagePath, p.ProductID
    FROM Products p
    INNER JOIN Categories c ON c.CategoryID = p.CategoryID
    LEFT JOIN ProductVariants pv ON pv.ProductID = p.ProductID
    LEFT JOIN OrderItems oi ON oi.ProductVariantID = pv.ProductVariantID
        AND EXISTS (SELECT 1 FROM Payments pay WHERE pay.OrderID = oi.OrderID
            AND pay.PaymentStatus = N'PAID' AND pay.PaidAt >= @Start AND pay.PaidAt < @End)
    GROUP BY p.ProductID, p.ProductName, p.IsAvailable, c.IsAvailable;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Analytics_ReadCategories
    @Start DATETIME2(7),
    @End DATETIME2(7)
AS
BEGIN
    SET NOCOUNT OFF;
    SELECT c.CategoryName, COALESCE(SUM(oi.Quantity), 0),
        COALESCE(SUM(oi.UnitPrice * oi.Quantity), 0), c.CategoryID
    FROM Categories c LEFT JOIN Products p ON p.CategoryID = c.CategoryID
    LEFT JOIN ProductVariants pv ON pv.ProductID = p.ProductID
    LEFT JOIN OrderItems oi ON oi.ProductVariantID = pv.ProductVariantID
        AND EXISTS (SELECT 1 FROM Payments pay WHERE pay.OrderID = oi.OrderID
            AND pay.PaymentStatus = N'PAID' AND pay.PaidAt >= @Start AND pay.PaidAt < @End)
    GROUP BY c.CategoryID, c.CategoryName ORDER BY 3 DESC, c.CategoryName;
END;
GO

-- Source rows follow exactly the same payment-date and created-order cohorts as the summary.
CREATE OR ALTER PROCEDURE dbo.Analytics_ReadDetails
    @Start DATETIME2(7), @End DATETIME2(7),
    @Items BIT, @Cohort BIT, @Status NVARCHAR(20) = NULL,
    @ProductID INT = 0, @CategoryID INT = 0, @Method NVARCHAR(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SELECT o.OrderID, o.OrderNumber, o.CreatedAt, p.PaidAt,
        COALESCE(p.PaymentMethod, N'') AS Method,
        CASE WHEN p.PaymentStatus = N'EXPIRED' OR
            (p.PaymentStatus = N'PENDING' AND o.ExpiresAt IS NOT NULL AND o.ExpiresAt <= SYSUTCDATETIME())
            THEN N'EXPIRED' ELSE COALESCE(p.PaymentStatus, N'NO_PAYMENT') END AS Status,
        COALESCE(p.Amount, 0) AS Amount,
        COALESCE(STUFF((SELECT N'; ' + pr.ProductName +
            COALESCE(N' (' + sz.SizeName + N')', N'') + N' × ' + CONVERT(NVARCHAR(12), line.Quantity)
            FROM dbo.OrderItems line
            INNER JOIN dbo.ProductVariants variant ON variant.ProductVariantID = line.ProductVariantID
            INNER JOIN dbo.Products pr ON pr.ProductID = variant.ProductID
            LEFT JOIN dbo.Sizes sz ON sz.SizeID = variant.SizeID
            WHERE line.OrderID = o.OrderID ORDER BY line.OrderItemID
            FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 2, N''), N'') AS Items
    INTO #Sources
    FROM dbo.Orders o LEFT JOIN dbo.Payments p ON p.OrderID = o.OrderID
    WHERE (@Cohort = 1 AND o.CreatedAt >= @Start AND o.CreatedAt < @End)
        OR (@Cohort = 0 AND p.PaymentStatus = N'PAID' AND p.PaidAt >= @Start AND p.PaidAt < @End);

    IF @Items = 1
        SELECT s.*, pr.ProductID, pr.ProductName, c.CategoryName,
            COALESCE(sz.SizeName, N'Regular') AS Size, oi.Quantity, oi.UnitPrice
        FROM #Sources s INNER JOIN dbo.OrderItems oi ON oi.OrderID = s.OrderID
        INNER JOIN dbo.ProductVariants pv ON pv.ProductVariantID = oi.ProductVariantID
        INNER JOIN dbo.Products pr ON pr.ProductID = pv.ProductID
        INNER JOIN dbo.Categories c ON c.CategoryID = pr.CategoryID
        LEFT JOIN dbo.Sizes sz ON sz.SizeID = pv.SizeID
        WHERE (@ProductID = 0 OR pr.ProductID = @ProductID)
            AND (@CategoryID = 0 OR c.CategoryID = @CategoryID)
        ORDER BY s.PaidAt DESC, s.OrderID DESC, oi.OrderItemID;
    ELSE
        SELECT * FROM #Sources
        WHERE (@Status IS NULL OR Status = @Status
            OR (@Status = N'AWAITING' AND Status NOT IN (N'PAID', N'EXPIRED')))
            AND (@Method IS NULL OR Method = @Method)
        ORDER BY COALESCE(PaidAt, CreatedAt) DESC, OrderID DESC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.Analytics_ReadPaymentMethods
    @Start DATETIME2(7),
    @End DATETIME2(7)
AS
BEGIN
    SET NOCOUNT OFF;
    SELECT PaymentMethod, COUNT(*), SUM(Amount)
    FROM Payments WHERE PaymentStatus = N'PAID' AND PaidAt >= @Start AND PaidAt < @End
    GROUP BY PaymentMethod ORDER BY 3 DESC;
END;
GO
